product1 = Product("harry potter", 100, "amozeshi", 10)
product2 = Product("pen" , 10, "books and needs", 50)
product3 = Product("lebas", 200, "poshak", 20)
product4 = Product("leili majnon", 300, "amozeshi", 30)
product5 = Product("khosro shirin", 300, "amozeshi", 30)
product6 = Product("divan of hafez", 300, "amozeshi", 30)
product7 = Product("saba", 300, "amozeshi", 30)
products = Products()
customer = Customer()
products.add_product(product1)
products.add_product(product2)
products.add_product(product3)
products.add_product(product4)
products.add_product(product5)
products.add_product(product6)
products.add_product(product7)